# Generated by Django 5.1.7 on 2025-04-18 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='membre',
            fields=[
                ('idMembre', models.BigAutoField(db_column='idMembre', primary_key=True, serialize=False)),
                ('nom', models.CharField(blank=True, db_column='nom', max_length=50, null=True)),
                ('prenom', models.CharField(blank=True, db_column='prenom', max_length=50, null=True)),
                ('anneeNais', models.SmallIntegerField(blank=True, db_column='anneeNais', null=True)),
                ('anneeEntree', models.SmallIntegerField(blank=True, null=True)),
                ('nbDeFemmes', models.IntegerField(db_column='nbDeFemmes')),
                ('login', models.CharField(db_column='login', max_length=50, unique=True)),
                ('password', models.CharField(blank=True, db_column='password', max_length=50, null=True)),
                ('sexe', models.CharField(max_length=1)),
                ('nomEpoux', models.CharField(blank=True, db_column='nomEpoux', max_length=50, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=15, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('actif', models.IntegerField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=50, null=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'membre',
            },
        ),
        migrations.CreateModel(
            name='tontines',
            fields=[
                ('idTontines', models.AutoField(db_column='idTontines', primary_key=True, serialize=False)),
                ('nomTontines', models.CharField(db_column='nomTontines', max_length=45)),
                ('typeTontine', models.CharField(db_column='typeTontine', max_length=45)),
                ('montantTontine', models.DecimalField(db_column='montantTontine', decimal_places=5, max_digits=20)),
                ('Datecreation', models.DateField(blank=True, db_column='dateCreation', null=True)),
            ],
            options={
                'db_table': 'tontines',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='epargne',
            fields=[
                ('idEpargne', models.AutoField(db_column='idEpargne', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=4, max_digits=19)),
                ('modeVersement', models.CharField(db_column='modeVersement', max_length=20)),
                ('couponVersement', models.CharField(blank=True, db_column='couponVersement', max_length=64, null=True, unique=True)),
                ('idSeance', models.BigIntegerField(db_column='idSeance')),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'epargne',
            },
        ),
        migrations.CreateModel(
            name='aide',
            fields=[
                ('numAide', models.AutoField(db_column='numAide', primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, db_column='date', null=True)),
                ('motif_aide', models.CharField(blank=True, db_column='motif_aide', max_length=50, null=True)),
                ('montantAide', models.DecimalField(db_column='montantAide', decimal_places=2, max_digits=15)),
                ('nomBeneficiaire', models.CharField(db_column='nomBeneficiaire', max_length=50)),
                ('lienBeneficiareAvecMembre', models.CharField(db_column='lienBeneficiareAvecMembre', max_length=50)),
                ('type_aide', models.CharField(blank=True, db_column='type_aide', max_length=50, null=True)),
                ('lieu', models.CharField(blank=True, db_column='lieu', max_length=255, null=True)),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'aide',
            },
        ),
        migrations.CreateModel(
            name='pret',
            fields=[
                ('idpret', models.BigAutoField(db_column='idpret', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observations', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En Cours'), ('rembourse', 'Remboursé')], max_length=50)),
                ('pourcentage', models.DecimalField(decimal_places=2, max_digits=15)),
                ('idSeance', models.BigIntegerField(db_column='idSeance')),
                ('idSeance_1', models.BigIntegerField(db_column='idSeance_1')),
                ('idMembre_avaliste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_avaliste', to='Association_tontine.membre')),
                ('idMembre_preteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prets_preteur', to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'pret',
            },
        ),
        migrations.CreateModel(
            name='remboursement',
            fields=[
                ('idRembo', models.BigAutoField(db_column='idRembo', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('idSeance', models.BigIntegerField(db_column='idSeance')),
                ('idpret', models.ForeignKey(db_column='idpret', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.pret')),
            ],
            options={
                'db_table': 'remboursement',
            },
        ),
        migrations.CreateModel(
            name='sanction',
            fields=[
                ('idSanction', models.AutoField(db_column='idSanction', primary_key=True, serialize=False)),
                ('dateSanction', models.DateField(db_column='dateSanction')),
                ('typeSanction', models.CharField(db_column='typeSanction', max_length=50)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('raison', models.TextField()),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'sanction',
            },
        ),
        migrations.CreateModel(
            name='membre_tontine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.tontines')),
            ],
            options={
                'db_table': 'association',
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='tontine',
            field=models.ManyToManyField(blank=True, related_name='membres', through='Association_tontine.membre_tontine', to='Association_tontine.tontines'),
        ),
        migrations.CreateModel(
            name='don',
            fields=[
                ('iddon', models.AutoField(db_column='iddon', primary_key=True, serialize=False)),
                ('nature_don', models.CharField(max_length=255)),
                ('date_don', models.DateField()),
                ('montant_don', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description_don', models.CharField(max_length=255)),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
                ('idTontines', models.ForeignKey(db_column='idTontines', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.tontines')),
            ],
            options={
                'db_table': 'don',
            },
        ),
        migrations.CreateModel(
            name='cotisation',
            fields=[
                ('codeCotisation', models.BigAutoField(db_column='codeCotisation', primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=15)),
                ('nbPartMax', models.IntegerField(blank=True, db_column='nbPartMax', null=True)),
                ('penaliteDefaillanceBenef', models.DecimalField(blank=True, db_column='penaliteDefaillanceBenef', decimal_places=2, max_digits=15, null=True)),
                ('penaliteDefaillanceNonBenef', models.DecimalField(blank=True, db_column='penaliteDefaillanceNonBenef', decimal_places=2, max_digits=15, null=True)),
                ('miseAPrix', models.DecimalField(db_column='miseAPrix', decimal_places=4, max_digits=19)),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
                ('tontine', models.ForeignKey(db_column='tontines', on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.tontines')),
            ],
            options={
                'db_table': 'cotisation',
            },
        ),
        migrations.AddField(
            model_name='membre',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.user'),
        ),
        migrations.CreateModel(
            name='versementcotis',
            fields=[
                ('idVersCotis', models.AutoField(db_column='idVersCotis', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modeVersement', models.CharField(db_column='modeVersement', max_length=20)),
                ('couponVersement', models.CharField(blank=True, db_column='couponVersement', max_length=64, null=True, unique=True)),
                ('idSeance', models.BigIntegerField(db_column='idSeance')),
                ('codeCotisation', models.ForeignKey(db_column='codeCotisation', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.cotisation')),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'versementcotis',
            },
        ),
        migrations.CreateModel(
            name='versementsol',
            fields=[
                ('idVersSol', models.AutoField(db_column='idVersSol', primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=15)),
                ('modeVersement', models.CharField(db_column='modeVersement', max_length=20)),
                ('couponVersement', models.CharField(blank=True, db_column='couponVersement', max_length=64, null=True, unique=True)),
                ('idSeance', models.BigIntegerField(db_column='idSeance')),
                ('idMembre', models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre')),
            ],
            options={
                'db_table': 'versementSol',
            },
        ),
    ]
