# Generated by Django 5.1.7 on 2025-04-26 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='tontine',
        ),
        migrations.AddField(
            model_name='remboursement',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Association_tontine.membre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membre',
            name='Tontine',
            field=models.ManyToManyField(blank=True, related_name='membres', through='Association_tontine.membre_tontine', to='Association_tontine.tontines'),
        ),
        migrations.AddField(
            model_name='membre',
            name='tontine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.tontines'),
        ),
    ]
