# Generated by Django 5.1.7 on 2025-04-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0002_remove_membre_tontine_remboursement_idmembre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='password',
            field=models.CharField(blank=True, db_column='password', max_length=128, null=True),
        ),
    ]
