# Generated by Django 5.1.7 on 2025-04-26 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0003_alter_membre_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
