# Generated by Django 5.1.7 on 2025-04-27 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0004_membre_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.user'),
        ),
    ]
