# Generated by Django 5.1.7 on 2025-04-28 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0006_alter_membre_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aide',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='aides', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='cotisations', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='don',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='dons', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='epargnes', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='remboursements', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='sanctions', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='versementcotis',
            name='codeCotisation',
            field=models.ForeignKey(db_column='codeCotisation', on_delete=django.db.models.deletion.DO_NOTHING, related_name='versementcotisa', to='Association_tontine.cotisation'),
        ),
        migrations.AlterField(
            model_name='versementsol',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.DO_NOTHING, related_name='versementsols', to='Association_tontine.membre'),
        ),
    ]
