# Generated by Django 5.1.7 on 2025-04-28 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0007_alter_aide_idmembre_alter_cotisation_idmembre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='Tontine',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='tontine',
        ),
        migrations.AddField(
            model_name='tontines',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tontine', to='Association_tontine.membre'),
            preserve_default=False,
        ),
    ]
