# Generated by Django 5.1.7 on 2025-05-03 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0008_remove_membre_tontine_remove_membre_tontine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.membre')),
                ('tontine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.tontines')),
            ],
            options={
                'db_table': 'association',
            },
        ),
        migrations.DeleteModel(
            name='membre_tontine',
        ),
    ]
