# Generated by Django 5.1.7 on 2025-05-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0009_association_delete_membre_tontine'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='association',
            table='Association',
        ),
    ]
