# Generated by Django 5.1.7 on 2025-05-03 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0010_alter_association_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='association',
            old_name='membres',
            new_name='membre',
        ),
    ]
