# Generated by Django 5.1.7 on 2025-05-03 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0011_rename_membres_association_membre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='membre',
        ),
        migrations.AddField(
            model_name='association',
            name='membres',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.membre'),
            preserve_default=False,
        ),
    ]
