# Generated by Django 5.1.7 on 2025-05-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0012_remove_association_membre_association_membres'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nbDeFemmes',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='nomEpoux',
        ),
        migrations.RemoveField(
            model_name='membre',
            name='password',
        ),
        migrations.AddField(
            model_name='membre',
            name='engagement',
            field=models.CharField(choices=[('marie(e)', 'Marie(e)'), ('celibataire', 'Celibataire'), ('divorce(e)', 'Divorce(e)')], default='Marie', max_length=50),
            preserve_default=False,
        ),
    ]
