# Generated by Django 5.1.7 on 2025-05-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0013_remove_membre_email_remove_membre_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membre',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
