# Generated by Django 5.1.7 on 2025-05-07 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0015_alter_membre_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aide',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='aides', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='cotisation',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='cotisations', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='don',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='dons', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='don',
            name='idTontines',
            field=models.ForeignKey(db_column='idTontines', on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.tontines'),
        ),
        migrations.AlterField(
            model_name='epargne',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='epargnes', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='sanctions', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='tontines',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='tontine', to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='versementcotis',
            name='codeCotisation',
            field=models.ForeignKey(db_column='codeCotisation', on_delete=django.db.models.deletion.CASCADE, related_name='versementcotisa', to='Association_tontine.cotisation'),
        ),
        migrations.AlterField(
            model_name='versementcotis',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, to='Association_tontine.membre'),
        ),
        migrations.AlterField(
            model_name='versementsol',
            name='idMembre',
            field=models.ForeignKey(db_column='idMembre', on_delete=django.db.models.deletion.CASCADE, related_name='versementsols', to='Association_tontine.membre'),
        ),
    ]
