# Generated by Django 5.1.7 on 2025-05-08 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0016_alter_aide_idmembre_alter_cotisation_idmembre_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tontines',
            name='idMembre',
        ),
        migrations.RemoveField(
            model_name='tontines',
            name='typeTontine',
        ),
        #migrations.AddField(
         #   model_name='cotisation',
         #   name='montant',
          #  field=models.DecimalField(decimal_places=4, default=1, max_digits=19),
           # preserve_default=False,
        #),
        #migrations.AddField(
        #    model_name='membre',
         #   name='tontine',
        #    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Association_tontine.tontines'),
        #),
        #migrations.AddField(
        #    model_name='pret',
         #   name='montant_remboursement',
          #  field=models.DecimalField(decimal_places=2, default=1, max_digits=15),
           # preserve_default=False,
        #),
        migrations.AddField(
            model_name='remboursement',
            name='date_remboursement',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='idpret',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='Association_tontine.pret'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('super_utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_super_utilisateur', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_utilisateur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_envoi'],
            },
        ),
    ]
