# Generated by Django 5.1.7 on 2025-05-14 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0017_remove_tontines_idmembre_remove_tontines_typetontine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='association',
            new_name='TontinesMembres',
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={},
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='remboursement',
            old_name='montant',
            new_name='montant_rembourse',
        ),
        migrations.RenameField(
            model_name='tontinesmembres',
            old_name='tontine',
            new_name='tontines',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='super_utilisateur',
        ),
        migrations.AddField(
            model_name='cotisation',
            name='date_paiement',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='est_valide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cotisation',
            name='montant',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotisation',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='don',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epargne',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='type_modification',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pret',
            name='date_demande',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pret',
            name='est_rembourse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pret',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remboursement',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sanction',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tontines',
            name='libelle',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tontines',
            name='membres',
            field=models.ManyToManyField(related_name='tontines', through='Association_tontine.TontinesMembres', to='Association_tontine.membre'),
        ),
        migrations.AddField(
            model_name='tontines',
            name='montant_obligatoire',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
        migrations.AddField(
            model_name='tontines',
            name='type_tontine',
            field=models.CharField(choices=[('S', 'Tontine Spéciale Journalière'), ('A', 'Tontine A 2000'), ('B', 'Tontine B 5000'), ('C', 'Tontine C 10000'), ('D', 'Tontine D 100000')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementcotis',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versementsol',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membre',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_envoi',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='date_remboursement',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='remboursement',
            name='idpret',
            field=models.ForeignKey(db_column='idpret', on_delete=django.db.models.deletion.CASCADE, related_name='remboursements', to='Association_tontine.pret'),
        ),
        migrations.AlterModelTable(
            name='tontinesmembres',
            table='tontines_membres',
        ),
    ]
