# Generated by Django 5.1.7 on 2025-05-24 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0018_rename_association_tontinesmembres_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeModification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('Tontine', 'Tontine'), ('Pret', 'Prêt'), ('Remboursement', 'Remboursement'), ('Epargne', 'Épargne'), ('Don', 'Don')], max_length=20)),
                ('donnees', models.JSONField()),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validée', 'Validée'), ('Refusée', 'Refusée')], default='En attente', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
