# Generated by Django 5.1.7 on 2025-05-24 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0019_demandemodification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En Attente'), ('valide', 'Validé'), ('refuse', 'Refusé')], default='en_attente', max_length=20),
        ),
    ]
