# Generated by Django 5.1.7 on 2025-05-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0020_alter_notification_date_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pret',
            name='cni_avaliste',
            field=models.FileField(blank=True, null=True, upload_to='documents_cni/'),
        ),
    ]
