# Generated by Django 5.1.7 on 2025-05-25 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Association_tontine', '0021_pret_cni_avaliste'),
    ]

    operations = [
        migrations.AlterUniqueTogether(name='tontinesmembres',unique_together=set(),),
    ]
